// Code generated by enumerator. DO NOT EDIT.

package example

import (
	"database/sql/driver"
	"fmt"
)

type Status struct {
	v statusEnum
}

var (
	Success   = Status{success}
	Failure   = Status{failure}
	Inbetween = Status{inBetween}
	Notsure   = Status{notSure}
)

func (r Status) String() string {
	return string(r.v)
}
func (r Status) MarshalText() ([]byte, error) {
	return []byte(r.v), nil
}
func (r *Status) UnmarshalText(in []byte) error {
	s, err := NewStatus(string(in))
	if err != nil {
		return err
	}
	*r = s
	return nil
}
func (r Status) Value() (driver.Value, error) {
	return r.v, nil
}
func (r *Status) Scan(in any) error {
	s, err := NewStatus(fmt.Sprint(in))
	if err != nil {
		return err
	}
	*r = s
	return nil
}
func NewStatus(in string) (Status, error) {
	switch in {
	case "success":
		return Success, nil
	case "failure":
		return Failure, nil
	case "inBetween":
		return Inbetween, nil
	case "notSure":
		return Notsure, nil
	default:
		return Status{}, fmt.Errorf("invalid value for type 'Status': '%s'", in)
	}
}
